### ISSUE TITLE
bug: 拒绝合并无关的历史

### ISSUE THREAD

**Issue by mingshewhe** [TencentBlueKing/ci-git-checkout#23]
当同时开启preMerge+depth=1时，比如develop分支合并master分支，如果develop分支先merge master，然后再向master发起mr请求，就会出现"fatal: 拒绝合并无关的历史"
![image](https://user-images.githubusercontent.com/22971705/150292137-d8de2481-7088-43c6-bfac-948209964fb8.png)

![image](https://user-images.githubusercontent.com/22971705/152466342-e50cc439-6c8e-43bd-9856-c062cbac9da8.png)
develop和master的公共祖先节点是m1，当通过--shallow-since拉取时，develop分支只拉取了d2，d3，d2有两个父节点，导致无法merge,只需把d1拉下来就能合并

解决策略:
1. 先通过--shallow-since拉取
2. 计算m1到d3之间的提交数，提交数+1就能得到d1的深度
3. 再次通过depth拉取源分支就能得到d1节点

**Comment by pmathticol** [comment]
+1
