### ISSUE TITLE
1 Error: Process completed with exit code 2199001: [Finish task] status: failure, errorType: 3, errorCode: 2199001, message: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.. Please contact the plugin developer.

### ISSUE THREAD

**Issue by Ymars1990** [TencentBlueKing/ci-git-checkout#66]
![image](https://user-images.githubusercontent.com/4321103/175476248-bafb60c4-8e2e-4d6d-9b14-f8686e48af72.png)
如图，并发时会发生这种错误，频率还挺高的

**Comment by mingshewhe** [comment]
插件升级到https://github.com/TencentBlueKing/ci-checkout/releases/tag/untagged-905a22811610bacca83d 这个版本可以解决
